# Author(s): Pieter.Kempeneers@ec.europa.eu,
#            Ondrej Pesek,
#            Pierre.Soille@ec.europa.eu
# Copyright (C) 2018-2026 European Union (Joint Research Centre)
#
# This file is part of pyjeo.
#
# pyjeo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pyjeo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyjeo.  If not, see <https://www.gnu.org/licenses/>.

[build-system]
requires = [
    "scikit-build-core>=0.5",
#    "setuptools",
#    "swig",
    "numpy"
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.args = [
    "-DCMAKE_BUILD_TYPE=Release",
    # Wijs modern CMake direct naar de Boost systeemmappen van AlmaLinux
    "-DBOOST_ROOT=/usr",
    "-DBoost_NO_BOOST_CMAKE=ON"
]

[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-* cp313-*"
skip = "*-musllinux_* *i686"

# LINUX (AlmaLinux 8 / RedHat basis)
[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
# 1. Activeer EPEL repository (nodig voor gdal, gsl, fann, etc.)
# 2. Installeer alle RedHat equivalenten van jouw library lijst via dnf
before-all = """
dnf install -y epel-release && \
dnf install -y make cmake gcc-c++ \
gsl-devel \
fann-devel \
libgeotiff-devel \
fftw-devel \
proj-devel \
jsoncpp-devel \
gdal-devel \
openssl-devel \
swig \
uthash-devel \
openblas-devel \
shapelib-devel \
boost-devel
"""

# MACOS
[tool.cibuildwheel.macos]
before-all = "brew install cmake gsl fann libgeotiff fftw proj jsoncpp gdal openssl swig openblas shapelib boost"

[metadata]
name = 'pyjeo'
version = '1.2.1'

[tool.setuptools.packages]

find = {}  # Scan the project directory with the default parameters

[project]
name = 'pyjeo'
version = '1.2.1'
description = 'pyjeo is a library for image processing for geospatial data implemented in JRC Ispra.'
authors = [
        { name = "Pieter Kempeneers", email = "Pieter.Kempeneers@ec.europa.eu"},
        { name = "Ondrej Pesek", email = "pesej.ondrek@gmail.com"},
        { name = "Pierre Soille", email = "Pierre.Soille@ec.europa.eu"},
]
requires-python = ">=3.8"
license = {text = "GPLv3"}
dependencies = ['numpy', 'rasterio', 'pandas', 'shapely', 'xarray', 'rioxarray', 'netCDF4', 'pyproj']

[project.urls]
documentation = 'https://readthedocs.org/projects/pyjeo'
repository = 'https://github.com/ec-jrc/jeolib-pyjeo'
