FROM registry.hub.docker.com/library/debian:10 as pyjeo-dev

LABEL project="pyjeo" \
      author="Pieter Kempeneers" \
      image_name="deb10_pyjeo_public" \
      version="0.1.3" \
      released="2021-06-28" \
      software_versions="Debian:10 Python:3.7 gdal:2.4.0 pyjeo:1.0.4"\
      description="multi-stage build for pyjeo"
      
ARG NCPU=4

RUN apt-get update \
  && apt-get upgrade -y \
  && DEBIAN_FRONTEND=noninteractive  apt-get install -y  --no-install-recommends \
    apt-utils \
    build-essential \
    cmake \
    libgdal-dev \
    make \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-wheel \
    python-pip-whl \
    sqlite3 \
    swig \
    zlib1g-dev \
    libgeotiff-dev \
    libgsl0-dev \
    libfann-dev \
    libfftw3-dev \
    libshp-dev \
    uthash-dev \
    libjsoncpp-dev \
    libboost-serialization-dev \
    libboost-filesystem-dev \
    python3-setuptools \
    libtool \
    python3-xarray \
    python3-netcdf4 \
    curl \
    git \
    gzip \
    tar \
    unzip \
  && rm -rf /var/lib/apt/lists/*
   

#
# Download and compile libraries
#  

# Env vars for paths, library versions
ENV INSTALL_HOME=/home/install

# Prepare compilation directory
RUN mkdir $INSTALL_HOME


RUN echo "install mial, jiplib, and pyjeo"

#
# Download and compile libraries
#  

RUN curl -L --output $INSTALL_HOME/mial.tar.gz https://github.com/ec-jrc/jeolib-miallib/archive/refs/tags/v1.0.0.tar.gz --verbose

# - mial
RUN set -xe \
    && cd $INSTALL_HOME \
    && tar xzvf mial.tar.gz \
    && cd $INSTALL_HOME/jeolib-miallib* \
    && make generic \
    && make install-generic \
    && ldconfig \
    && cd $INSTALL_HOME \
    && rm mial.tar.gz \
    && rm -rf $INSTALL_HOME/jeolib-miallib*

RUN curl -L --output $INSTALL_HOME/jiplib.tar.gz https://github.com/ec-jrc/jeolib-jiplib/archive/refs/tags/1.0.5.tar.gz --verbose

# - jiplib
RUN set -xe \
    && cd $INSTALL_HOME \
    && tar xzvf jiplib.tar.gz \
    && cd $INSTALL_HOME/jeolib-jiplib* \
    && mkdir build \
    && cd build \
    && cmake .. \
    && sleep 5 \
    && make -j $NCPU \
    && make install \
    && ldconfig \
    && cd $INSTALL_HOME \
    && rm jiplib.tar.gz \
    && rm -rf $INSTALL_HOME/jeolib-jiplib*

RUN curl -L --output $INSTALL_HOME/pyjeo.tar.gz https://github.com/ec-jrc/jeolib-pyjeo/archive/refs/tags/1.0.4.tar.gz --verbose

# - pyjeo
RUN cd $INSTALL_HOME \
    && tar xzvf pyjeo.tar.gz \
    && cd $INSTALL_HOME/jeolib-pyjeo* \
    && python3 setup.py install \
    && cd $INSTALL_HOME \
    && rm -rf $INSTALL_HOME/jeolib-pyjeo*
    #&& rm pyjeo.tar.gz

FROM registry.hub.docker.com/library/debian:10 as pyjeo

# Env vars for paths, library versions
ENV INSTALL_HOME=/home/install

RUN apt-get update \
  && apt-get upgrade -y \
  && DEBIAN_FRONTEND=noninteractive  apt-get install -y  --no-install-recommends \
    apt-utils \
    python3-setuptools \
    libboost-serialization1.67.0 \
    libboost-filesystem1.67.0 \
    libjsoncpp1 \
    gsl-bin \
    libfann2 \
    fftw3 \
    libshp2 \
    gdal-bin \
    libpython3.7 \
    python3 \
    python3-gdal \
    python3-numpy \
    python3-wheel \
    python3-xarray \
    python3-netcdf4 \
    gzip \
    tar \
  && rm -rf /var/lib/apt/lists/*

RUN \
  mkdir -p /usr/local/lib/python3.7/dist-packages/jiplib

COPY --from=pyjeo-dev /usr/local/lib/python3.7/dist-packages/pyjeo-1.0.4-py3.7.egg /usr/local/lib/python3.7/dist-packages
COPY --from=pyjeo-dev /usr/local/lib/python3.7/dist-packages/jiplib/__init__.py /usr/local/lib/python3.7/dist-packages/jiplib
COPY --from=pyjeo-dev /usr/local/lib/python3.7/dist-packages/jiplib/_jiplib.so /usr/local/lib/python3.7/dist-packages/jiplib
COPY --from=pyjeo-dev /usr/local/lib/python3.7/dist-packages/jiplib/jiplib.py /usr/local/lib/python3.7/dist-packages/jiplib
COPY --from=pyjeo-dev /usr/local/lib/libmiallib_generic.so /usr/local/lib
COPY --from=pyjeo-dev /usr/local/lib/libjiplib.so.1.0.5 /usr/local/lib

COPY --from=pyjeo-dev $INSTALL_HOME/pyjeo.tar.gz /usr/local/share

# - pyjeo
RUN cd /usr/local/share \
    && tar xzvf pyjeo.tar.gz \
    && cd jeolib-pyjeo* \
    && python3 setup.py install \
    && cd /usr/local/share \
    && rm pyjeo.tar.gz

RUN \
  cd /usr/local/lib/ \
  && ln -s libjiplib.so.1.0.5 libjiplib.so.1 \
  && ln -s libjiplib.so.1 libjiplib.so \
  && cd /usr/local/share/jeolib-pyjeo* \
  && python3 setup.py install

FROM pyjeo AS pyjeo_prod

RUN rm -rf /usr/local/share/jeolib-pyjeo*
