FROM registry.hub.docker.com/library/debian:11 as pyjeo-dev

LABEL project="pyjeo" \
      author="Pieter Kempeneers" \
      image_name="deb10_pyjeo_public" \
      version="0.1.4" \
      released="2022-06-11" \
      software_versions="Debian:11 Python:3.9.2 gdal:3.2.2 pyjeo:1.0.8"\
      description="multi-stage build for pyjeo"
      
ARG NCPU=4

RUN apt-get update \
  && apt-get upgrade -y \
  && DEBIAN_FRONTEND=noninteractive  apt-get install -y  --no-install-recommends \
    apt-utils \
    build-essential \
    cmake \
    libgdal-dev \
    make \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-wheel \
    python-pip-whl \
    sqlite3 \
    swig \
    zlib1g-dev \
    libgeotiff-dev \
    libgsl0-dev \
    libfann-dev \
    libfftw3-dev \
    libshp-dev \
    uthash-dev \
    libjsoncpp-dev \
    libboost-serialization-dev \
    libboost-filesystem-dev \
    python3-setuptools \
    libtool \
    python3-xarray \
    python3-netcdf4 \
    python3-pyproj \
    python3-gdal \
    curl \
    git \
    gzip \
    tar \
    unzip \
  && rm -rf /var/lib/apt/lists/*
   

#
# Download and compile libraries
#  

# Env vars for paths, library versions
ENV INSTALL_HOME=/home/install

# Prepare compilation directory
RUN mkdir $INSTALL_HOME


RUN echo "install mial, jiplib, and pyjeo"

#
# Download and compile libraries
#  
RUN curl -L --output $INSTALL_HOME/mial.tar.gz https://github.com/ec-jrc/jeolib-miallib/archive/refs/tags/v1.0.2.tar.gz --verbose

# - mial
RUN set -xe \
    && cd $INSTALL_HOME \
    && tar xzvf mial.tar.gz \
    && cd $INSTALL_HOME/jeolib-miallib* \
    && make generic \
    && make install-generic \
    && ldconfig \
    && cd $INSTALL_HOME \
    && rm mial.tar.gz \
    && rm -rf $INSTALL_HOME/jeolib-miallib*

RUN curl -L --output $INSTALL_HOME/jiplib.tar.gz https://github.com/ec-jrc/jeolib-jiplib/archive/refs/tags/v1.0.8.tar.gz --verbose

# - jiplib
RUN set -xe \
    && cd $INSTALL_HOME \
    && tar xzvf jiplib.tar.gz \
    && cd $INSTALL_HOME/jeolib-jiplib* \
    && mkdir build \
    && cd build \
    && cmake .. \
    && sleep 5 \
    && make -j $NCPU \
    && make install \
    && ldconfig \
    && cd $INSTALL_HOME \
    && rm jiplib.tar.gz \
    && rm -rf $INSTALL_HOME/jeolib-jiplib*

RUN curl -L --output $INSTALL_HOME/pyjeo.tar.gz https://github.com/ec-jrc/jeolib-pyjeo/archive/refs/tags/v1.0.8.tar.gz --verbose

# - pyjeo
RUN cd $INSTALL_HOME \
    && tar xzvf pyjeo.tar.gz \
    && cd $INSTALL_HOME/jeolib-pyjeo* \
    && python3 setup.py install \
    && cd $INSTALL_HOME \
    && rm -rf $INSTALL_HOME/jeolib-pyjeo*
    #&& rm pyjeo.tar.gz

RUN rm -rf /usr/local/share/jeolib-pyjeo*
